# -*- coding: utf-8 -*-
"""19CY20025_linearRegression.ipynb

Author : Nishant Yadav
ID : 19CY20025
Created on : 27/08/2022

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EDPNyhfA1obFtaDEyYnj8YEdnlzi1tgX
"""

import pandas as pd

# This is directory in my pc where .csv is located
# This is to be changed according to the file location in user's pc
df = pd.read_csv('~/Downloads/data.csv')

# Storing the columns of .csv file into arrays
x = df.iloc[:,0].values
y = df.iloc[:,1].values

# Getting size of arrays
n = len(y)

# Summation of xi and yi
sum_x = x.sum()  
sum_y = y.sum()

# Summation of xi*yi
sum_xy = 0
for i in range(n):
    sum_xy = sum_xy + x[i]*y[i]

# Summation of squares of xi
sum_x2 = 0
for i in range(n):
    sum_x2 = sum_x2 + x[i]**2

# print(sum_x)
# print(sum_y)
# print(sum_x2)
# print(sum_xy)

# Slope of linear curve
m = (n*sum_xy - sum_x*sum_y)/(n*sum_x2 - sum_x**2)

# y intercept of linear curve
b = (sum_y - m*sum_x)/n

print("slope: ", m)
print("y-intercept: ", b)
print("The equation of line is y =", m, "(x) +", b)